### PR TITLE
hacktoberfest: Update model id for workers ai

### PR DESCRIPTION
**Pull request by Mrinank-Bhowmick**
Fixes: #81

### CODE REVIEW

**Review by narengogi — APPROVED** [review]

**Comment by vrushankportkey** [comment]
@Mrinank-Bhowmick this is a small enough change. We can qualify is as hacktoberfest-accepted but it would not be eligible for Portkey prizes. Is that ok?

**Comment by Mrinank-Bhowmick** [comment]
@vrushankportkey 

👀 I appreciate the hacktoberfest-accepted tag, but I spent time investigating and fixing this issue, which was documented on the official docs site. I believe it deserves consideration for the Portkey prizes, and I'd appreciate it if you could take that into account. Thanks!

**Comment by Mrinank-Bhowmick** [comment]
@vrushankportkey @narengogi 
Any updates?

**Comment by vrushankportkey** [comment]
We'll get back!

**Pull request merged**
